# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 09:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InstituteAlias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='InstituteMatches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('city', models.CharField(default=b'None', max_length=40)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(default=b'India', max_length=30)),
                ('established', models.IntegerField(default=0)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('modified_on', models.DateTimeField(auto_now=True)),
                ('type_of_institute', models.CharField(default=b'None', max_length=5)),
                ('misc', models.CharField(blank=True, max_length=100, null=True)),
                ('is_normalized', models.BooleanField(default=True)),
                ('modified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UnnormalizedInstitute',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='institutematches',
            name='normalized_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norm_string_set', to='overseer.NormalizedInstitute'),
        ),
        migrations.AddField(
            model_name='institutematches',
            name='unnormalized_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unnorm_string_set', to='overseer.NormalizedInstitute'),
        ),
        migrations.AddField(
            model_name='institutealias',
            name='ins_alias_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alias_set', to='overseer.UnnormalizedInstitute'),
        ),
        migrations.AddField(
            model_name='institutealias',
            name='normalized_institute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='norm_set', to='overseer.NormalizedInstitute'),
        ),
    ]
