# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-15 06:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_percentile', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='String',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=244)),
                ('normalized_id', models.IntegerField(blank=True, null=True)),
                ('is_parent', models.BooleanField(default=False)),
                ('is_normalized', models.BooleanField(default=False)),
                ('is_abbreviation', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Institute',
            fields=[
                ('string_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='overseer.String')),
            ],
            bases=('overseer.string',),
        ),
        migrations.AddField(
            model_name='string',
            name='children',
            field=models.ManyToManyField(related_name='_string_children_+', to='overseer.String'),
        ),
        migrations.AddField(
            model_name='match',
            name='string_one',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_one_set', to='overseer.String'),
        ),
        migrations.AddField(
            model_name='match',
            name='string_two',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='string_two_set', to='overseer.String'),
        ),
    ]
