# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-05 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('overseer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='institutematches',
            name='unnormalized_inst',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unnorm_string_set', to='overseer.UnnormalizedInstitute'),
        ),
    ]
