# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseer', '0002_string_is_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='has_match',
            field=models.BooleanField(default=False),
        ),
    ]
