# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-22 06:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overseer', '0003_string_has_match'),
    ]

    operations = [
        migrations.AddField(
            model_name='string',
            name='no_of_matches',
            field=models.IntegerField(default=0),
        ),
    ]
